features = [
    "street",
    "postal_code",
    "city",
    "neighborhood",
    "type",
    "description",
    "price",
    "utilities_price",
    "moving_in_price",
    "type",
    "area",
    "rooms",
    "floor",
    "furnished",
    "sharing friendly",
    "pets allowed",
    "Elevator",
    "senior friendly",
    "only students",
    "balcony/terrace",
    "parking",
    "dishwasher",
    "washing maching",
    "charging stand",
    "dryer",
    "energy label"
]